### PR TITLE
Adding private key to check_ping()

### PR DESCRIPTION
**Pull request by inhumantsar**

### CODE REVIEW

**Comment by inhumantsar** [comment]
For #37

**Comment by inhumantsar** [comment]
I should also mention that this is completely untested ;)

**Comment by Smana** [comment]
```
+++ b/src/kargo/deploy.py
@@ -122,7 +122,7 @@ class RunPlaybook(object):
             '-b', '--become-user=root', '-m', 'ping', 'all',
             '-i', self.inventorycfg
         ]
-        if self.options['sshkey']:
+        if 'sshkey' in self.options.keys():
             cmd = cmd + ['--private-key', self.options['sshkey']]
         if self.options['coreos']:
             cmd = cmd + ['-e', 'ansible_python_interpreter=/opt/bin/python']
```

**Comment by Smana** [comment]
when the change above will be added, this PR can be merged

**Comment by inhumantsar** [comment]
Pushed that change up in the same branch as used in PR #40.. Closing this one.

**Pull request closed without merging**
