### PR TITLE
Added OpenStack support

### PR DESCRIPTION
**Pull request by TeutoNet**

### CODE REVIEW

**Comment by TeutoNet** [comment]
We can provide you an account to our own OpenStack Public Cloud either for testing of the pull request or CI testing.

**Comment by Smana** [comment]
Great job again @ocaner-biz @TeutoNet  !
Unfortunately i can't test it as i don't have an OpenStack platform.

I'll just check that nothing's broken and will merge it :)

**Comment by Smana** [comment]
Oh i didn't see your message, yes we would appreciate to do tests on your platform, you can send me the information using my personnal email : smainklh@gmail.com

**Comment by Smana** [comment]
@TeutoNet Could you please update the README  too please ?

**Comment by Smana** [comment]
Thanks, i didn't tested it on your platform yet (i'll try to), but there's no regression for the other arguments.

**Pull request merged**
